name: "Testing Post Job"
description: "Testing Post Job"

inputs:
  mode:
    description: "Mode"
    required: false
  job_status:
    description: "Job"
    required: false
    default: 'unknown'

runs:
  using: "composite"
  steps:
    - name: Run main logic
      shell: bash
      run: |        
          bash "${{ github.action_path }}/post.sh" "$JOB_STATUS"
        else
          bash "${{ github.action_path }}/main.sh"
        fi
