name: "Testing Post Job"
description: "Testing Post Job"

inputs:
  gh_token:
    description: 'GitHub token'
    required: true
  mode:
    description: 'Action mode'
    default: 'run'
  job_status:
    description: 'Job status'
    required: false
  pse_job_id:
    description: 'PSE Job ID'
    required: false
  all_job_ids:
    description: 'All Job IDs'
    required: false

runs:
  using: "composite"
  steps:
    - name: Execute Script Based on Mode  # This is now the primary (and only) step
      shell: bash
      run: |
        if [ "${{ inputs.mode }}" = "cleanup" ]; then
          echo "JOB DETAILS FROM ACTION.YML----------------------"
          bash "${{ github.action_path }}/get_job_status.sh"
        elif [ "${{ inputs.mode }}" = "analyze" ]; then
          echo "Running analysis logic..."
          bash "${{ github.action_path }}/get_logs.sh"
        else
          bash "${{ github.action_path }}/main.sh"
        fi
      env:
        # Use inputs directly. The default for github_token is handled in the inputs section.
        # The syntax `inputs.github_token || github.token` is not standard for env context.
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JOB_IDS: ${{ inputs.all_job_ids }} # This will be the ID of the job in the workflow calling this action
        # You can also pass other inputs as environment variables if your scripts expect them:
        # INPUT_MODE: ${{ inputs.mode }}
        # INPUT_JOB_STATUS: ${{ inputs.job_status }}
