name: "Testing Post Job"
description: "Testing Post Job"

inputs:
  mode:
    description: "Mode"
    required: false
  job_status:
    description: "Job"
    required: false
    default: 'unknown'
  github_token:
    description: 'GitHub token to be passed to the PSE container for GitHub authentication'
    required: false
    default: ${{ github.token }}


runs:
  using: "composite"
  steps:
    - name: Run main logic
      shell: bash
      run: |        
          bash "${{ github.action_path }}/get_job_status.sh"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        JOB_ID: ${{github.job_id}}
