name: 'My Action'
description: 'Custom GitHub Action with log analysis'
author: 'Your Name'

inputs:
  mode:
    description: 'Action mode'
    default: 'run'
    required: true
  gh_token:
    description: 'GitHub token'
    required: true
  job_status:
    description: 'Status of the job'
    required: false
  pse_job_id:
    description: 'Job ID for PSE'
    required: false
  all_job_ids:
    description: 'Comma-separated list of all job IDs'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run Analysis
      shell: bash
      run: |
        if [ "${{ inputs.mode }}" = "analyze" ]; then
          echo "JOB DETAILS FROM ACTION.YML----------------------"
          echo "--------------------------------------------------"
          echo "PRINT STEP SUMMARY FROM ACTION.YML----------------------"
          # Pass the job status to your script
          JOB_STATUS=${JOB_STATUS:-"${{ inputs.job_status }}"}
          bash "${{ github.action_path }}/get_log.sh"
        else
          bash "${{ github.action_path }}/main.sh"
        fi
      env:
        MODE: ${{ inputs.mode }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        JOB_STATUS: ${{ inputs.job_status }}
        PSE_JOB_ID: ${{ inputs.pse_job_id }}
        ALL_JOB_IDS: ${{ inputs.all_job_ids }}
        GITHUB_REPOSITORY: ${{ github.repository }}
