name: "Testing Post Job"
description: "Testing Post Job"

inputs:
  mode:
    description: "Mode"
    required: false
    default: ''
  job_status:
    description: "Job"
    required: false
    default: 'unknown'
  github_token:
    description: 'GitHub token to be passed to the PSE container for GitHub authentication'
    required: false
    default: ${{ github.token }}


runs:
  using: "composite"
  steps:
    - name: Run main logic
      shell: bash
      - name: Execute Script Based on Mode
        run: |
          if [ "${{ inputs.mode }}" = "cleanup" ]; then
            echo "JOB DETAILS FROM ACTION.YML----------------------"
            bash "${{ github.action_path }}/get_job_status.sh"
          elif [ "${{ inputs.mode }}" = "analyze" ]; then
            echo "Running analysis logic..."
            bash "${{ github.action_path }}/get_logs.sh"
          else
            bash "${{ github.action_path }}/main.sh"
          fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        JOB_ID: ${{github.job}}
