name: Run PSE Clean Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pse:
    runs-on: ubuntu-latest
    outputs:
      pse_job_id: ${{ steps.get-job-ids.outputs.current_job_id }}
      all_job_ids: ${{ steps.get-job-ids.outputs.all_job_ids }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Job IDs
        id: get-job-ids
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
          all_ids=$(echo "$jobs" | jq -r '.jobs[].id' | tr '\n' ',' | sed 's/,$//')
          current_id=$(echo "$jobs" | jq -r ".jobs[] | select(.name == \"${{ github.job }}\") | .id")
          echo "current_job_id=$current_id" >> $GITHUB_OUTPUT
          echo "all_job_ids=$all_ids" >> $GITHUB_OUTPUT

  get_logs:
    runs-on: ubuntu-latest
    needs: pse
    steps:
      - uses: actions/checkout@v3
      
      - name: Run log analysis
        id: log_analysis
        if: always()
        uses: ./.github/actions/my-action
        with:
          mode: analyze
          job_status: ${{ job.status }}
          pse_job_id: ${{ needs.pse.outputs.pse_job_id }}
          all_job_ids: ${{ needs.pse.outputs.all_job_ids }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
