name: Run PSE Clean Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pse:
    runs-on: ubuntu-latest
    outputs:
      pse_job_id: ${{ steps.get-job-id.outputs.job_id }} # Declare pse_job_id as an output of this job

    steps:
      - uses: actions/checkout@v3

      - name: Run Custom Action
        uses: ./.github/actions/my-action
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}

      # - name: Sample failed step
      #   run: exit 1
      - name: Get Job ID from GH API
        id: get-job-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: Display Job ID
        run: |
            echo Job ID: ${{ steps.get-job-id.outputs.job_id }}
            echo My full job URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}

  get_logs:
    runs-on: ubuntu-latest
    needs: pse # Ensure get_logs depends on pse
    steps:
      - uses: actions/checkout@v3
      - name: Run post cleanup
        if: always()
        uses: ./.github/actions/my-action
        with:
          mode: analyze
          job_status: ${{job.status}}
          # Access the job_id from the 'pse' job's outputs
          pse_logs: ${{ needs.pse.outputs.pse_job_id }}
