name: Run PSE Clean Action

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  pse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Custom Action
        uses: ./.github/actions/my-action

      - name: Sample failed step
        run: exit 1

      - name: Run post cleanup
        if: always()
        uses: ./.github/actions/my-action
        with:
          mode: cleanup
          status: ${{job.status}}
