name: Run PSE Clean Action

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  pse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Custom Action
        uses: ./.github/actions/my-action
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}

      # - name: Sample failed step
      #   run: exit 1
  get_logs:
    runs-on: ubuntu-latest
    needs: pse
    steps:
      - uses: actions/checkout@v3
      - name: Run post cleanup
        if: always()
        uses: ./.github/actions/my-action
        with:
          mode: cleanup
          job_status: ${{job.status}}
